---
title: "Assignment7_MSDS450_Group1"
author: "Andrew Bernier, Tyrone Brown and Allison Turner"
date: "6/1/2021"
output: html_document
---

```{r cars}
library(bayesm)
```

```{r Import Data}
data(tuna)
summary(tuna)

# Get Log of Sales
tuna$LMOVE1 <- log(tuna$MOVE1)
tuna$LMOVE2 <- log(tuna$MOVE2)
tuna$LMOVE3 <- log(tuna$MOVE3)
tuna$LMOVE4 <- log(tuna$MOVE4)
tuna$LMOVE5 <- log(tuna$MOVE5)
tuna$LMOVE6 <- log(tuna$MOVE6)
tuna$LMOVE7 <- log(tuna$MOVE7)

```

``` {r Price Elasticity Models}

# Regression for each brand's cross price elasticity
m11 <- lm(LMOVE1 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m12 <- lm(LMOVE2 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m13 <- lm(LMOVE3 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m14 <- lm(LMOVE4 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m15 <- lm(LMOVE5 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m16 <- lm(LMOVE6 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)
m17 <- lm(LMOVE7 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = tuna)

# Create df of all alphas
sales_elasticity <- rbind(
  m11$coefficients[2:8], 
  m12$coefficients[2:8], 
  m13$coefficients[2:8], 
  m14$coefficients[2:8], 
  m15$coefficients[2:8], 
  m16$coefficients[2:8], 
  m17$coefficients[2:8]
)

row.names(sales_elasticity) <- c('SALES1','SALES2','SALES3','SALES4','SALES5','SALES6','SALES7')
colnames(sales_elasticity) <- c('PRICE1','PRICE2','PRICE3','PRICE4','PRICE5','PRICE6','PRICE7')

sales_elasticity
```

```{r Competitive Mapping Using Sales}
library("psych")

pc.cr <- princomp(sales_elasticity, cor=TRUE)
biplot(pc.cr)
```

```{r Market Share Models}
library(mlogit)

# Get Market Shares for each Brand

# Compute Geometric mean of sales for all brands
tuna$SALES_GEO_MEAN <- apply(tuna[,2:8], 1, function(x) (prod(x[x!=0]))^(1/sum(x!=0)))

# Ratio of each brand's sales vs. geometric mean
tuna$SHARE1 <- tuna$MOVE1 / tuna$SALES_GEO_MEAN
tuna$SHARE2 <- tuna$MOVE2 / tuna$SALES_GEO_MEAN
tuna$SHARE3 <- tuna$MOVE3 / tuna$SALES_GEO_MEAN
tuna$SHARE4 <- tuna$MOVE4 / tuna$SALES_GEO_MEAN
tuna$SHARE5 <- tuna$MOVE5 / tuna$SALES_GEO_MEAN
tuna$SHARE6 <- tuna$MOVE6 / tuna$SALES_GEO_MEAN
tuna$SHARE7 <- tuna$MOVE7 / tuna$SALES_GEO_MEAN

# Log of Shares (Will be response variable in regression)
tuna$LSHARE1 <- log(tuna$SHARE1)
tuna$LSHARE2 <- log(tuna$SHARE2)
tuna$LSHARE3 <- log(tuna$SHARE3)
tuna$LSHARE4 <- log(tuna$SHARE4)
tuna$LSHARE5 <- log(tuna$SHARE5)
tuna$LSHARE6 <- log(tuna$SHARE6)
tuna$LSHARE7 <- log(tuna$SHARE7)

# Brand Share Elasticities

# Brand 1
Share_Elasticity_B1 <- cbind(tuna$LSHARE1,tuna[,16:22])
colnames(Share_Elasticity_B1)[1] <- 'LSHARE1'
Share_Elasticity_B1$LPRICE1 <- (1-(1/7)) * Share_Elasticity_B1$LPRICE1
Share_Elasticity_B1$LPRICE2 <- (-(1/7)) * Share_Elasticity_B1$LPRICE2
Share_Elasticity_B1$LPRICE3 <- (-(1/7)) * Share_Elasticity_B1$LPRICE3
Share_Elasticity_B1$LPRICE4 <- (-(1/7)) * Share_Elasticity_B1$LPRICE4
Share_Elasticity_B1$LPRICE5 <- (-(1/7)) * Share_Elasticity_B1$LPRICE5
Share_Elasticity_B1$LPRICE6 <- (-(1/7)) * Share_Elasticity_B1$LPRICE6
Share_Elasticity_B1$LPRICE7 <- (-(1/7)) * Share_Elasticity_B1$LPRICE7

# Brand 2
Share_Elasticity_B2 <- cbind(tuna$LSHARE2,tuna[,16:22])
colnames(Share_Elasticity_B2)[1] <- 'LSHARE2'
Share_Elasticity_B2$LPRICE1 <- (-(1/7)) * Share_Elasticity_B2$LPRICE1
Share_Elasticity_B2$LPRICE2 <- (1-(1/7)) * Share_Elasticity_B2$LPRICE2
Share_Elasticity_B2$LPRICE3 <- (-(1/7)) * Share_Elasticity_B2$LPRICE3
Share_Elasticity_B2$LPRICE4 <- (-(1/7)) * Share_Elasticity_B2$LPRICE4
Share_Elasticity_B2$LPRICE5 <- (-(1/7)) * Share_Elasticity_B2$LPRICE5
Share_Elasticity_B2$LPRICE6 <- (-(1/7)) * Share_Elasticity_B2$LPRICE6
Share_Elasticity_B2$LPRICE7 <- (-(1/7)) * Share_Elasticity_B2$LPRICE7

# Brand 3
Share_Elasticity_B3 <- cbind(tuna$LSHARE3,tuna[,16:22])
colnames(Share_Elasticity_B3)[1] <- 'LSHARE3'
Share_Elasticity_B3$LPRICE1 <- (-(1/7)) * Share_Elasticity_B3$LPRICE1
Share_Elasticity_B3$LPRICE2 <- (-(1/7)) * Share_Elasticity_B3$LPRICE2
Share_Elasticity_B3$LPRICE3 <- (1-(1/7)) * Share_Elasticity_B3$LPRICE3
Share_Elasticity_B3$LPRICE4 <- (-(1/7)) * Share_Elasticity_B3$LPRICE4
Share_Elasticity_B3$LPRICE5 <- (-(1/7)) * Share_Elasticity_B3$LPRICE5
Share_Elasticity_B3$LPRICE6 <- (-(1/7)) * Share_Elasticity_B3$LPRICE6
Share_Elasticity_B3$LPRICE7 <- (-(1/7)) * Share_Elasticity_B3$LPRICE7

# Brand 4
Share_Elasticity_B4 <- cbind(tuna$LSHARE4,tuna[,16:22])
colnames(Share_Elasticity_B4)[1] <- 'LSHARE4'
Share_Elasticity_B4$LPRICE1 <- (-(1/7)) * Share_Elasticity_B4$LPRICE1
Share_Elasticity_B4$LPRICE2 <- (-(1/7)) * Share_Elasticity_B4$LPRICE2
Share_Elasticity_B4$LPRICE3 <- (-(1/7)) * Share_Elasticity_B4$LPRICE3
Share_Elasticity_B4$LPRICE4 <- (1-(1/7)) * Share_Elasticity_B4$LPRICE4
Share_Elasticity_B4$LPRICE5 <- (-(1/7)) * Share_Elasticity_B4$LPRICE5
Share_Elasticity_B4$LPRICE6 <- (-(1/7)) * Share_Elasticity_B4$LPRICE6
Share_Elasticity_B4$LPRICE7 <- (-(1/7)) * Share_Elasticity_B4$LPRICE7

# Brand 5
Share_Elasticity_B5 <- cbind(tuna$LSHARE5,tuna[,16:22])
colnames(Share_Elasticity_B5)[1] <- 'LSHARE5'
Share_Elasticity_B5$LPRICE1 <- (-(1/7)) * Share_Elasticity_B5$LPRICE1
Share_Elasticity_B5$LPRICE2 <- (-(1/7)) * Share_Elasticity_B5$LPRICE2
Share_Elasticity_B5$LPRICE3 <- (-(1/7)) * Share_Elasticity_B5$LPRICE3
Share_Elasticity_B5$LPRICE4 <- (-(1/7)) * Share_Elasticity_B5$LPRICE4
Share_Elasticity_B5$LPRICE5 <- (1-(1/7)) * Share_Elasticity_B5$LPRICE5
Share_Elasticity_B5$LPRICE6 <- (-(1/7)) * Share_Elasticity_B5$LPRICE6
Share_Elasticity_B5$LPRICE7 <- (-(1/7)) * Share_Elasticity_B5$LPRICE7

# Brand 6
Share_Elasticity_B6 <- cbind(tuna$LSHARE6,tuna[,16:22])
colnames(Share_Elasticity_B6)[1] <- 'LSHARE6'
Share_Elasticity_B6$LPRICE1 <- (-(1/7)) * Share_Elasticity_B6$LPRICE1
Share_Elasticity_B6$LPRICE2 <- (-(1/7)) * Share_Elasticity_B6$LPRICE2
Share_Elasticity_B6$LPRICE3 <- (-(1/7)) * Share_Elasticity_B6$LPRICE3
Share_Elasticity_B6$LPRICE4 <- (-(1/7)) * Share_Elasticity_B6$LPRICE4
Share_Elasticity_B6$LPRICE5 <- (-(1/7)) * Share_Elasticity_B6$LPRICE5
Share_Elasticity_B6$LPRICE6 <- (1-(1/7)) * Share_Elasticity_B6$LPRICE6
Share_Elasticity_B6$LPRICE7 <- (-(1/7)) * Share_Elasticity_B6$LPRICE7

# Brand 7
Share_Elasticity_B7 <- cbind(tuna$LSHARE7,tuna[,16:22])
colnames(Share_Elasticity_B7)[1] <- 'LSHARE7'
Share_Elasticity_B7$LPRICE1 <- (-(1/7)) * Share_Elasticity_B7$LPRICE1
Share_Elasticity_B7$LPRICE2 <- (-(1/7)) * Share_Elasticity_B7$LPRICE2
Share_Elasticity_B7$LPRICE3 <- (-(1/7)) * Share_Elasticity_B7$LPRICE3
Share_Elasticity_B7$LPRICE4 <- (-(1/7)) * Share_Elasticity_B7$LPRICE4
Share_Elasticity_B7$LPRICE5 <- (-(1/7)) * Share_Elasticity_B7$LPRICE5
Share_Elasticity_B7$LPRICE6 <- (-(1/7)) * Share_Elasticity_B7$LPRICE6
Share_Elasticity_B7$LPRICE7 <- (1-(1/7)) * Share_Elasticity_B7$LPRICE7

# Regression for each brand's cross price elasticity
m21 <- lm(LSHARE1 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B1)
m22 <- lm(LSHARE2 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B2)
m23 <- lm(LSHARE3 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B3)
m24 <- lm(LSHARE4 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B4)
m25 <- lm(LSHARE5 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B5)
m26 <- lm(LSHARE6 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B6)
m27 <- lm(LSHARE7 ~ LPRICE1 + LPRICE2 + LPRICE3 + LPRICE4 + LPRICE5 + LPRICE6 + LPRICE7, data = Share_Elasticity_B7)

# Create df of all alphas
share_elasticity <- rbind(
  m21$coefficients[2:8], 
  m22$coefficients[2:8], 
  m23$coefficients[2:8], 
  m24$coefficients[2:8], 
  m25$coefficients[2:8], 
  m26$coefficients[2:8], 
  m27$coefficients[2:8]
)

row.names(share_elasticity) <- c('SHARE1','SHARE2','SHARE3','SHARE4','SHARE5','SHARE6','SHARE7')
colnames(share_elasticity) <- c('PRICE1','PRICE2','PRICE3','PRICE4','PRICE5','PRICE6','PRICE7')

share_elasticity
```

```{r Competitive Mapping Using Share}

pc.cr <- princomp(share_elasticity, cor=TRUE)
biplot(pc.cr)
```